### ISSUE TITLE
Improve ETL form

### ISSUE THREAD

**Issue by evinracher** [nietoga/nietoga-com#7]
Integrate material UI and formik forms in ETL form

**Comment by nietoga** [comment]
Dude, we're not using `formik` but `react-hook-form`

**Comment by evinracher** [comment]
> Dude, we're not using `formik` but `react-hook-form`

Sure collegue

**Comment by nietoga** [comment]
See:

* https://github.com/nietoga/nietoga-com/pull/11
* https://github.com/nietoga/nietoga-com/pull/3
* https://github.com/nietoga/nietoga-com/pull/2
* https://github.com/nietoga/nietoga-com/issues/12
